version: '3.8'

services:

  vinted-discord-bot:
    build: .
    environment:
      VINTED_BOT_ADMIN_IDS: "${VINTED_BOT_ADMIN_IDS}"
      VINTED_BOT_TOKEN: "${VINTED_BOT_TOKEN}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

#volumes:
