version: '3.8'

services:

  vinted-discord-bot:
    image: vinted-discord-bot:3.0
    environment:
      VINTED_BOT_ADMIN_IDS: "${VINTED_BOT_ADMIN_IDS}"
      VINTED_BOT_TOKEN: "${VINTED_BOT_TOKEN}"
      POSTGRES_DB: vinted_bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      DB_NAME: vinted_bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

#volumes:
